apiVersion: v1
kind: Service
metadata:
  name: templatemo-service
spec:
  type: LoadBalancer
  selector:
    app: templatemo-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
